{{- $relnamespace := .Release.Namespace }}
{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $relnamespace }}
type: Opaque
data:
  value: {{ .value | b64enc | quote }}
---
{{- end }}
