{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "etherpad.serviceAccountName" . }}
  labels:
{{ include "etherpad.labels" . | indent 4 }}
{{- end -}}
